---
image_name: "ninkasi"
#docker_build_root: "~/dev/misc/docker-build"
#build_home: "~/dev/workspaces/NA/{{image_name}}"
docker_build_root: "/var/lib/jenkins/docker"
build_home: "/var/lib/jenkins/workspace/Mosaic-Docker-Ninkasi"
registry_image_name: "registry.okina.fr/mosaic/{{image_name}}"
version: "0.5.12"

build_log_directory: "{{docker_build_root}}/logs"
image_docker_root: "{{docker_build_root}}/{{image_name}}"
logfile: "{{build_log_directory}}/{{image_name}}.log"