---

- include_vars: ~/.naq-credentials.yml

- name: Make log directory structure
  file: path={{build_log_directory}} state=directory mode=0755 group={{lookup('env', 'USER')}}

- name: Make ninkasi target directory structure
  file: path={{image_docker_root}}/ state=directory mode=0755 group={{lookup('env', 'USER')}}

- name: Copy the ninkasi sources to staging directory
  command: rsync -ar --delete {{ build_home }}/ {{image_docker_root}}/source

- name: Move Dockerfile
  template: src=Dockerfile.j2 dest={{image_docker_root}}/Dockerfile mode=0755

- name: Log into DockerHub
  docker_login:
    registry: registry.okina.fr
    username: "{{okina_docker_registry_user}}"
    password: "{{okina_docker_registry_password}}"
    reauthorize: yes

- name: Build the ninkasi docker image (this takes about 2 minutes)
  shell: docker build --tag={{ registry_image_name|quote }}:{{ version|quote }} --force-rm=true {{image_docker_root}} --build-arg SSH_KEY="$(cat ~/.ssh/id_rsa)" > {{logfile}} 2>&1
  register: image

- name: Push ninkasi docker image if built
  when: image.changed
  shell: docker push {{ registry_image_name|quote }}:{{ version|quote }}
